<?php

use App\Http\Controllers\AreaTaskController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SetupController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DrawingController;
use App\Http\Controllers\MeetstaatImportController;
use App\Http\Controllers\PlanningActionController;
use App\Http\Controllers\PlanningController;
use App\Http\Controllers\ProductionController;
use App\Http\Controllers\ProgressController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PublicSnagController;
use App\Http\Controllers\ScannedDimensionsImportController;
use App\Http\Controllers\ScreenExcelImportController;
use App\Http\Controllers\ShopProjectController;
use App\Http\Controllers\SmallWorkController;
use App\Http\Controllers\SnagController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VoucherController;
use App\Http\Controllers\WorkActivityCategoryController;
use App\Http\Controllers\WorkActivityController;
use App\Http\Controllers\WorkerAvailabilityController;
use App\Http\Controllers\WorkerController;
use App\Http\Controllers\WorkerRateController;
use App\Http\Middleware\EnsureProjectAccess;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return auth()->check()
        ? redirect()->route('dashboard')
        : redirect()->route('login');
});

Route::get('/login', [LoginController::class, 'create'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'store'])->middleware(['guest', 'throttle:login']);
Route::post('/logout', [LoginController::class, 'destroy'])->name('logout')->middleware('auth');

Route::middleware(['first-run', 'guest'])->group(function () {
    Route::get('/setup', [SetupController::class, 'create'])->name('setup.create');
    Route::post('/setup', [SetupController::class, 'store'])->middleware('throttle:setup')->name('setup.store');
});

Route::middleware('throttle:public-snag')->group(function () {
    Route::get('/oplever/{token}', [PublicSnagController::class, 'show'])->name('snags.public.show');
    Route::post('/oplever/{token}/opmerking', [PublicSnagController::class, 'comment'])->name('snags.public.comment');
    Route::post('/oplever/{token}/in-behandeling', [PublicSnagController::class, 'progress'])->name('snags.public.progress');
    Route::post('/oplever/{token}/gereed', [PublicSnagController::class, 'complete'])->name('snags.public.complete');
    Route::get('/oplever/{token}/foto/{photo}', [PublicSnagController::class, 'photo'])->name('snags.public.photo');
});

Route::middleware(['auth', EnsureProjectAccess::class])->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/planning', [PlanningController::class, 'index'])->name('planning');
    Route::get('/planning/candidates', [PlanningActionController::class, 'candidates'])->name('planning.candidates');
    Route::get('/planning/pdf', [PlanningController::class, 'export'])->name('planning.export');
    Route::get('/planning/weekplanning', [PlanningController::class, 'weekplanning'])->name('planning.weekplanning');
    Route::get('/planning/excel', [PlanningController::class, 'excel'])->name('planning.excel');
    Route::post('/planning/shift', [PlanningActionController::class, 'shift'])->name('planning.shift');
    Route::post('/planning/assignments/move', [PlanningActionController::class, 'moveAssignment'])->name('planning.assignments.move');
    Route::post('/planning/assignments', [PlanningActionController::class, 'storeAssignment'])->name('planning.assignments.store');
    Route::patch('/planning/assignments/{assignment}', [PlanningActionController::class, 'updateAssignment'])->name('planning.assignments.update');
    Route::delete('/planning/assignments/{assignment}', [PlanningActionController::class, 'destroyAssignment'])->name('planning.assignments.destroy');
    Route::get('/productie', [ProductionController::class, 'index'])->name('production.index');
    Route::post('/productie/akkoord', [ProductionController::class, 'approve'])->name('production.approve');
    Route::get('/productie/bonnen/nieuw', [VoucherController::class, 'create'])->name('vouchers.create');
    Route::post('/productie/bonnen', [VoucherController::class, 'store'])->name('vouchers.store');
    Route::get('/productie/bonnen/{voucher}/aanpassen', [VoucherController::class, 'edit'])->name('vouchers.edit');
    Route::patch('/productie/bonnen/{voucher}', [VoucherController::class, 'update'])->name('vouchers.update');
    Route::post('/productie/bonnen/{voucher}/mail', [VoucherController::class, 'send'])->middleware('throttle:voucher-mail')->name('vouchers.send');
    Route::get('/productie/bonnen/{voucher}', [VoucherController::class, 'show'])->name('vouchers.show');
    Route::get('/voortgang', [ProgressController::class, 'create'])->name('progress.create');
    Route::post('/voortgang', [ProgressController::class, 'store'])->name('progress.store');
    Route::get('/projecten', [ProjectController::class, 'index'])->name('projects.index');
    Route::get('/projecten/archief', [ProjectController::class, 'archived'])->name('projects.archived');
    Route::get('/projecten/nieuw', [ProjectController::class, 'create'])->name('projects.create');
    Route::get('/projecten/winkel/nieuw', [ShopProjectController::class, 'create'])->name('projects.winkel.create');
    Route::post('/projecten/winkel', [ShopProjectController::class, 'store'])->name('projects.winkel.store');
    Route::get('/projecten/klein/nieuw', [SmallWorkController::class, 'create'])->name('projects.small.create');
    Route::post('/projecten/klein', [SmallWorkController::class, 'store'])->name('projects.small.store');
    Route::patch('/projecten/klein/{project}', [SmallWorkController::class, 'update'])->name('projects.small.update');
    Route::get('/projecten/{project}/extra-werk/{workItem}', [SmallWorkController::class, 'editExtra'])->name('projects.extra.edit')->scopeBindings();
    Route::patch('/projecten/{project}/extra-werk/{workItem}', [SmallWorkController::class, 'updateExtra'])->name('projects.extra.update')->scopeBindings();
    Route::post('/projecten/inlezen', [MeetstaatImportController::class, 'preview'])->name('projects.preview');
    Route::get('/projecten/controle/{token}', [MeetstaatImportController::class, 'review'])->name('projects.review');
    Route::post('/projecten/controle/{token}', [MeetstaatImportController::class, 'import'])->name('projects.import');
    Route::get('/projecten/zonwering/{token}', [ScreenExcelImportController::class, 'review'])->name('projects.screens.review');
    Route::post('/projecten/zonwering/{token}', [ScreenExcelImportController::class, 'import'])->name('projects.screens.import');
    Route::post('/projecten/afmetingen/inlezen', [ScannedDimensionsImportController::class, 'previewFromForm'])->name('projects.afmetingen.preview');
    Route::get('/projecten/afmetingen/{token}', [ScannedDimensionsImportController::class, 'review'])->name('projects.afmetingen.review');
    Route::post('/projecten/afmetingen/{token}', [ScannedDimensionsImportController::class, 'import'])->name('projects.afmetingen.import');
    Route::post('/projecten', [ProjectController::class, 'store'])->name('projects.store');
    Route::get('/projecten/meetstaat-voorbeeld.csv', [ProjectController::class, 'template'])->name('projects.template');
    Route::get('/projecten/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::patch('/projecten/{project}', [ProjectController::class, 'update'])->name('projects.update');
    Route::patch('/projecten/{project}/winkel', [ShopProjectController::class, 'update'])->name('projects.winkel.update');
    Route::post('/projecten/{project}/winkel/bijlagen', [ShopProjectController::class, 'storeAttachments'])->name('projects.winkel.attachments.store');
    Route::delete('/projecten/{project}/winkel/bijlagen/{document}', [ShopProjectController::class, 'destroyAttachment'])->name('projects.winkel.attachments.destroy');
    Route::post('/projecten/{project}/archiveren', [ProjectController::class, 'archive'])->name('projects.archive');
    Route::post('/projecten/{project}/terugzetten', [ProjectController::class, 'restore'])->name('projects.restore');
    Route::delete('/projecten/{project}', [ProjectController::class, 'destroy'])->name('projects.destroy');
    Route::post('/projecten/{project}/meetstaat', [ProjectController::class, 'storeMeetstaat'])->name('projects.meetstaat.store');
    Route::post('/projecten/{project}/opdrachtlijst', [ScreenExcelImportController::class, 'storeOnProject'])->name('projects.screens.store');
    Route::post('/projecten/{project}/plattegrond', [ProjectController::class, 'storePlattegrond'])->name('projects.plattegrond.store');
    Route::get('/projecten/{project}/documenten/{document}', [ProjectController::class, 'document'])->name('projects.documents.show');
    Route::post('/projecten/{project}/opdrachten', [ProjectController::class, 'storeOrder'])->name('projects.orders.store');
    Route::post('/projecten/{project}/taken/{areaTask}/gereed', [AreaTaskController::class, 'complete'])->name('projects.tasks.complete');
    Route::post('/projecten/{project}/ruimtes/details', [DrawingController::class, 'details'])->name('projects.areas.details');
    Route::post('/projecten/{project}/ruimtes/{area}/afvinken', [AreaTaskController::class, 'tick'])->name('projects.areas.tick');
    Route::get('/projecten/{project}/ruimtes/{area}', [DrawingController::class, 'area'])->name('projects.areas.show');
    Route::post('/projecten/{project}/ruimtes/{area}/onderdeel', [DrawingController::class, 'completeGroup'])->name('projects.areas.group');
    Route::post('/projecten/{project}/ruimtes/{area}/verwerken', [DrawingController::class, 'process'])->name('projects.areas.process');
    Route::post('/projecten/{project}/ruimtes/{area}/heropenen', [DrawingController::class, 'reopen'])->name('projects.areas.reopen');
    Route::post('/projecten/{project}/ruimtes/{area}/akkoord', [DrawingController::class, 'approve'])->name('projects.areas.approve');
    Route::post('/projecten/{project}/werkzaamheden/verwerken', [DrawingController::class, 'processMany'])->name('projects.work.process');
    Route::post('/projecten/{project}/werkzaamheden/heropenen', [DrawingController::class, 'reopenMany'])->name('projects.work.reopen');
    Route::post('/projecten/{project}/werkzaamheden/akkoord', [DrawingController::class, 'approveMany'])->name('projects.work.approve');
    Route::post('/projecten/{project}/ruimtes/{area}/marker', [DrawingController::class, 'place'])->name('projects.areas.marker');
    Route::post('/projecten/{project}/tekeningen/{document}/zoeken', [DrawingController::class, 'detect'])->name('projects.drawings.detect');
    Route::get('/projecten/{project}/opleverpunten', [SnagController::class, 'index'])->name('projects.snags.index');
    Route::get('/projecten/{project}/opleverpunten/pdf', [SnagController::class, 'export'])->name('projects.snags.export');
    Route::post('/projecten/{project}/opleverpunten', [SnagController::class, 'store'])->name('projects.snags.store');
    Route::get('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'show'])->name('projects.snags.show');
    Route::patch('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'update'])->name('projects.snags.update');
    Route::delete('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'destroy'])->name('projects.snags.destroy');
    Route::post('/projecten/{project}/opleverpunten/{snag}/foto', [SnagController::class, 'photo'])->name('projects.snags.photos.store');
    Route::get('/projecten/{project}/opleverpunten/{snag}/foto/{photo}', [SnagController::class, 'file'])->name('projects.snags.photo');
    Route::post('/projecten/{project}/opleverpunten/{snag}/gereed', [SnagController::class, 'report'])->name('projects.snags.report');
    Route::post('/projecten/{project}/opleverpunten/{snag}/goedkeuren', [SnagController::class, 'approve'])->name('projects.snags.approve');
    Route::post('/projecten/{project}/opleverpunten/{snag}/afkeuren', [SnagController::class, 'reject'])->name('projects.snags.reject');
    Route::get('/gebruikers', [UserController::class, 'index'])->name('users.index');
    Route::get('/gebruikers/nieuw', [UserController::class, 'create'])->name('users.create');
    Route::post('/gebruikers', [UserController::class, 'store'])->name('users.store');
    Route::get('/gebruikers/{user}', [UserController::class, 'show'])->name('users.show');
    Route::patch('/gebruikers/{user}', [UserController::class, 'update'])->name('users.update');
    Route::delete('/gebruikers/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('/beheer/werkzaamheden', [WorkActivityController::class, 'index'])->name('work-activities.index');
    Route::post('/beheer/werkzaamheden', [WorkActivityController::class, 'store'])->name('work-activities.store');
    Route::patch('/beheer/werkzaamheden/{activity}', [WorkActivityController::class, 'update'])->name('work-activities.update');
    Route::post('/beheer/werkzaamheden/categorieen', [WorkActivityCategoryController::class, 'store'])->name('work-activity-categories.store');
    Route::patch('/beheer/werkzaamheden/categorieen/{category}', [WorkActivityCategoryController::class, 'update'])->name('work-activity-categories.update');
    Route::get('/vakmensen', [WorkerController::class, 'index'])->name('workers.index');
    Route::get('/vakmensen/nieuw', [WorkerController::class, 'create'])->name('workers.create');
    Route::post('/vakmensen', [WorkerController::class, 'store'])->name('workers.store');
    Route::post('/vakmensen/vakkennis', [WorkerController::class, 'storeSpecialty'])->name('workers.specialties.store');
    Route::get('/vakmensen/{worker}', [WorkerController::class, 'show'])->name('workers.show');
    Route::patch('/vakmensen/{worker}', [WorkerController::class, 'update'])->name('workers.update');
    Route::patch('/vakmensen/{worker}/vrijdag', [WorkerAvailabilityController::class, 'updateFriday'])->name('workers.friday.update');
    Route::patch('/vakmensen/{worker}/beschikbaarheid', [WorkerAvailabilityController::class, 'updateFlags'])->name('workers.availability.update');
    Route::post('/vakmensen/{worker}/beschikbaarheid', [WorkerAvailabilityController::class, 'store'])->name('workers.availability.store');
    Route::delete('/vakmensen/{worker}/beschikbaarheid/{availability}', [WorkerAvailabilityController::class, 'destroy'])->scopeBindings()->name('workers.availability.destroy');
    Route::post('/vakmensen/{worker}/prijzen', [WorkerRateController::class, 'store'])->name('workers.rates.store');
    Route::get('/ploegen', [TeamController::class, 'index'])->name('teams.index');
    Route::post('/ploegen', [TeamController::class, 'store'])->name('teams.store');
});
