<?php

use App\Http\Controllers\AreaTaskController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\SetupController;
use App\Http\Controllers\Auth\VakmanLoginController;
use App\Http\Controllers\Auth\VakmanPasswordController;
use App\Http\Controllers\CalculationController;
use App\Http\Controllers\CalculationLineController;
use App\Http\Controllers\CalculationWorkbookController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DrawingController;
use App\Http\Controllers\MeetstaatImportController;
use App\Http\Controllers\PlanningActionController;
use App\Http\Controllers\PlanningController;
use App\Http\Controllers\ProductionController;
use App\Http\Controllers\ProgressController;
use App\Http\Controllers\ProjectController;
use App\Http\Controllers\PublicSnagController;
use App\Http\Controllers\ScannedDimensionsImportController;
use App\Http\Controllers\ScreenExcelImportController;
use App\Http\Controllers\ShopProjectController;
use App\Http\Controllers\SmallWorkController;
use App\Http\Controllers\SnagController;
use App\Http\Controllers\SourceUpdateController;
use App\Http\Controllers\TeamController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\VakmanPlanningController;
use App\Http\Controllers\VoucherController;
use App\Http\Controllers\WorkActivityCategoryController;
use App\Http\Controllers\WorkActivityController;
use App\Http\Controllers\WorkerAvailabilityController;
use App\Http\Controllers\WorkerController;
use App\Http\Controllers\WorkerCrewMemberController;
use App\Http\Controllers\WorkerLoginInviteController;
use App\Http\Controllers\WorkerPdfImportController;
use App\Http\Controllers\WorkerPersonnelController;
use App\Http\Controllers\WorkerRateController;
use App\Http\Controllers\WorkTicketController;
use App\Http\Middleware\EnsureProjectAccess;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    if (! auth()->check()) {
        return redirect()->route('login');
    }

    return auth()->user()?->isVakman()
        ? redirect()->route('vakman.planning')
        : redirect()->route('dashboard');
});

Route::get('/login', [LoginController::class, 'create'])->name('login')->middleware('guest');
Route::post('/login', [LoginController::class, 'store'])->middleware(['guest', 'throttle:login']);
Route::get('/vakman/login', [VakmanLoginController::class, 'create'])->name('vakman.login')->middleware('guest');
Route::post('/vakman/login', [VakmanLoginController::class, 'store'])->name('vakman.login.store')->middleware(['guest', 'throttle:vakman-login']);
Route::post('/logout', [LoginController::class, 'destroy'])->name('logout')->middleware('auth');

Route::middleware(['first-run', 'guest'])->group(function () {
    Route::get('/setup', [SetupController::class, 'create'])->name('setup.create');
    Route::post('/setup', [SetupController::class, 'store'])->middleware('throttle:setup')->name('setup.store');
});

Route::middleware('throttle:public-snag')->group(function () {
    Route::get('/oplever/{token}', [PublicSnagController::class, 'show'])->name('snags.public.show');
    Route::get('/oplever/{token}/foto/{photo}', [PublicSnagController::class, 'photo'])->name('snags.public.photo');
});

Route::middleware('throttle:public-snag-write')->group(function () {
    Route::post('/oplever/{token}/opmerking', [PublicSnagController::class, 'comment'])->name('snags.public.comment');
    Route::post('/oplever/{token}/in-behandeling', [PublicSnagController::class, 'progress'])->name('snags.public.progress');
    Route::post('/oplever/{token}/gereed', [PublicSnagController::class, 'complete'])->name('snags.public.complete');
});

Route::middleware(['auth', EnsureProjectAccess::class])->group(function () {
    Route::get('/mijn-planning', [VakmanPlanningController::class, 'index'])->name('vakman.planning');
    Route::get('/mijn-planning/dag/{date}', [VakmanPlanningController::class, 'day'])->where('date', '\d{4}-\d{2}-\d{2}')->name('vakman.planning.day');
    Route::get('/mijn-planning/dag/{date}/werkbon', [VakmanPlanningController::class, 'werkbon'])->where('date', '\d{4}-\d{2}-\d{2}')->name('vakman.planning.werkbon');
    Route::get('/mijn-planning/dag/{date}/opdrachtbon/{project}', [VakmanPlanningController::class, 'opdrachtbon'])->where('date', '\d{4}-\d{2}-\d{2}')->name('vakman.planning.opdrachtbon');
    Route::get('/vakman/wachtwoord', [VakmanPasswordController::class, 'edit'])->name('vakman.password.edit');
    Route::patch('/vakman/wachtwoord', [VakmanPasswordController::class, 'update'])->middleware('throttle:vakman-password')->name('vakman.password.update');
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/planning', [PlanningController::class, 'index'])->name('planning');
    Route::get('/planning/candidates', [PlanningActionController::class, 'candidates'])->name('planning.candidates');
    Route::get('/planning/pdf', [PlanningController::class, 'export'])->name('planning.export');
    Route::get('/planning/weekplanning', [PlanningController::class, 'weekplanning'])->name('planning.weekplanning');
    Route::get('/planning/weekplanning-personeel', [PlanningController::class, 'personnelWeek'])->name('planning.personnel-week');
    Route::get('/planning/weekplanning-personeel/pdf', [PlanningController::class, 'personnelWeekPdf'])->name('planning.personnel-week.pdf');
    Route::get('/planning/excel', [PlanningController::class, 'excel'])->name('planning.excel');
    Route::post('/planning/shift', [PlanningActionController::class, 'shift'])->name('planning.shift');
    Route::post('/planning/assignments/move', [PlanningActionController::class, 'moveAssignment'])->name('planning.assignments.move');
    Route::post('/planning/assignments', [PlanningActionController::class, 'storeAssignment'])->name('planning.assignments.store');
    Route::patch('/planning/assignments/{assignment}', [PlanningActionController::class, 'updateAssignment'])->name('planning.assignments.update');
    Route::delete('/planning/assignments/{assignment}', [PlanningActionController::class, 'destroyAssignment'])->name('planning.assignments.destroy');
    Route::get('/planning/assignments/{assignment}/werkbonnen/nieuw', [WorkTicketController::class, 'create'])->name('work-tickets.create');
    Route::post('/planning/assignments/{assignment}/werkbonnen', [WorkTicketController::class, 'store'])->name('work-tickets.store');
    Route::get('/werkbonnen/{workTicket}', [WorkTicketController::class, 'show'])->name('work-tickets.show');
    Route::get('/werkbonnen/{workTicket}/pdf', [WorkTicketController::class, 'pdf'])->name('work-tickets.pdf');
    Route::patch('/werkbonnen/{workTicket}/uren', [WorkTicketController::class, 'updateHours'])->name('work-tickets.hours.update');
    Route::delete('/werkbonnen/{workTicket}', [WorkTicketController::class, 'destroy'])->name('work-tickets.destroy');
    Route::get('/productie', [ProductionController::class, 'index'])->name('production.index');
    Route::post('/productie/akkoord', [ProductionController::class, 'approve'])->name('production.approve');
    Route::get('/productie/bonnen/nieuw', [VoucherController::class, 'create'])->name('vouchers.create');
    Route::post('/productie/bonnen', [VoucherController::class, 'store'])->name('vouchers.store');
    Route::get('/productie/bonnen/{voucher}/aanpassen', [VoucherController::class, 'edit'])->name('vouchers.edit');
    Route::patch('/productie/bonnen/{voucher}', [VoucherController::class, 'update'])->name('vouchers.update');
    Route::post('/productie/bonnen/{voucher}/mail', [VoucherController::class, 'send'])->middleware('throttle:voucher-mail')->name('vouchers.send');
    Route::delete('/productie/bonnen/{voucher}', [VoucherController::class, 'destroy'])->name('vouchers.destroy');
    Route::get('/productie/bonnen/{voucher}/pdf', [VoucherController::class, 'pdf'])->name('vouchers.pdf');
    Route::get('/productie/bonnen/{voucher}', [VoucherController::class, 'show'])->name('vouchers.show');
    Route::get('/voortgang', [ProgressController::class, 'create'])->name('progress.create');
    Route::post('/voortgang', [ProgressController::class, 'store'])->name('progress.store');
    Route::get('/calculaties', [CalculationController::class, 'index'])->name('calculations.index');
    Route::get('/calculaties/nieuw', [CalculationController::class, 'create'])->name('calculations.create');
    Route::post('/calculaties', [CalculationController::class, 'store'])->name('calculations.store');
    Route::get('/calculaties/{calculation}/verwerken', [CalculationController::class, 'processing'])->name('calculations.processing');
    Route::get('/calculaties/{calculation}/verwerken/status', [CalculationController::class, 'importStatus'])->name('calculations.import-status');
    Route::get('/calculaties/{calculation}', [CalculationController::class, 'show'])->name('calculations.show');
    Route::get('/calculaties/{calculation}/bord', [CalculationController::class, 'board'])->name('calculations.board');
    Route::get('/calculaties/{calculation}/print-opties', [CalculationController::class, 'printOptions'])->name('calculations.print.options');
    Route::get('/calculaties/{calculation}/print', [CalculationController::class, 'print'])->name('calculations.print');
    Route::get('/calculaties/{calculation}/totalen', [CalculationController::class, 'totals'])->name('calculations.totals');
    Route::get('/calculaties/{calculation}/bronnen', [CalculationController::class, 'files'])->name('calculations.files');
    Route::patch('/calculaties/{calculation}/bord/ruimtes/{line}', [CalculationLineController::class, 'updateBoardRoom'])->name('calculations.board.rooms.update')->scopeBindings();
    Route::post('/calculaties/{calculation}/bord/ruimtes/{line}/bevestigen', [CalculationLineController::class, 'confirmBoardRoom'])->name('calculations.board.rooms.confirm')->scopeBindings();
    Route::patch('/calculaties/{calculation}', [CalculationController::class, 'update'])->name('calculations.update');
    Route::delete('/calculaties/{calculation}', [CalculationController::class, 'destroy'])->name('calculations.destroy');
    Route::get('/calculaties/{calculation}/klaar', [CalculationController::class, 'imported'])->name('calculations.imported');
    Route::get('/calculaties/{calculation}/excel-mapping', [CalculationWorkbookController::class, 'edit'])->name('calculations.workbooks.edit');
    Route::post('/calculaties/{calculation}/excel-mapping', [CalculationWorkbookController::class, 'update'])->name('calculations.workbooks.update');
    Route::get('/calculaties/{calculation}/excel', [CalculationController::class, 'excel'])->name('calculations.excel');
    Route::post('/calculaties/{calculation}/excel', [CalculationWorkbookController::class, 'store'])->name('calculations.workbooks.store');
    Route::get('/calculaties/{calculation}/excelbestanden/{workbook}', [CalculationWorkbookController::class, 'show'])->name('calculations.workbooks.show')->scopeBindings();
    Route::post('/calculaties/{calculation}/bevestig-volledig', [CalculationLineController::class, 'confirmComplete'])->name('calculations.confirm-complete');
    Route::post('/calculaties/{calculation}/regels/{line}/bevestigen', [CalculationLineController::class, 'confirm'])->name('calculations.lines.confirm')->scopeBindings();
    Route::get('/calculaties/{calculation}/tekeningen/{drawing}', [CalculationController::class, 'drawing'])->name('calculations.drawings.show')->scopeBindings();
    Route::post('/calculaties/{calculation}/regels', [CalculationLineController::class, 'store'])->name('calculations.lines.store');
    Route::delete('/calculaties/{calculation}/regels/{line}', [CalculationLineController::class, 'destroy'])->name('calculations.lines.destroy')->scopeBindings();
    Route::get('/projecten', [ProjectController::class, 'index'])->name('projects.index');
    Route::get('/projecten/pdf', [ProjectController::class, 'pdf'])->name('projects.pdf');
    Route::get('/projecten/archief', [ProjectController::class, 'archived'])->name('projects.archived');
    Route::get('/projecten/nieuw', [ProjectController::class, 'create'])->name('projects.create');
    Route::get('/projecten/winkel/nieuw', [ShopProjectController::class, 'create'])->name('projects.winkel.create');
    Route::get('/projecten/winkel/beschikbare-vakmannen', [ShopProjectController::class, 'availableWorkers'])->name('projects.winkel.available-workers');
    Route::post('/projecten/winkel', [ShopProjectController::class, 'store'])->name('projects.winkel.store');
    Route::get('/projecten/klein/nieuw', [SmallWorkController::class, 'create'])->name('projects.small.create');
    Route::post('/projecten/klein', [SmallWorkController::class, 'store'])->name('projects.small.store');
    Route::patch('/projecten/klein/{project}', [SmallWorkController::class, 'update'])->name('projects.small.update');
    Route::get('/projecten/{project}/extra-werk/{workItem}', [SmallWorkController::class, 'editExtra'])->name('projects.extra.edit')->scopeBindings();
    Route::patch('/projecten/{project}/extra-werk/{workItem}', [SmallWorkController::class, 'updateExtra'])->name('projects.extra.update')->scopeBindings();
    Route::post('/projecten/inlezen', [MeetstaatImportController::class, 'preview'])->name('projects.preview');
    Route::get('/projecten/controle/{token}', [MeetstaatImportController::class, 'review'])->name('projects.review');
    Route::post('/projecten/controle/{token}', [MeetstaatImportController::class, 'import'])->name('projects.import');
    Route::get('/projecten/zonwering/{token}', [ScreenExcelImportController::class, 'review'])->name('projects.screens.review');
    Route::post('/projecten/zonwering/{token}', [ScreenExcelImportController::class, 'import'])->name('projects.screens.import');
    Route::post('/projecten/afmetingen/inlezen', [ScannedDimensionsImportController::class, 'previewFromForm'])->name('projects.afmetingen.preview');
    Route::get('/projecten/afmetingen/{token}', [ScannedDimensionsImportController::class, 'review'])->name('projects.afmetingen.review');
    Route::post('/projecten/afmetingen/{token}', [ScannedDimensionsImportController::class, 'import'])->name('projects.afmetingen.import');
    Route::post('/projecten', [ProjectController::class, 'store'])->name('projects.store');
    Route::get('/projecten/meetstaat-voorbeeld.csv', [ProjectController::class, 'template'])->name('projects.template');
    Route::get('/projecten/{project}', [ProjectController::class, 'show'])->name('projects.show');
    Route::patch('/projecten/{project}', [ProjectController::class, 'update'])->name('projects.update');
    Route::patch('/projecten/{project}/winkel', [ShopProjectController::class, 'update'])->name('projects.winkel.update');
    Route::get('/projecten/{project}/winkel/inmeetformulier.pdf', [ShopProjectController::class, 'measurementPdf'])->name('projects.winkel.measurement.pdf');
    Route::get('/projecten/{project}/winkel/werkbon', [ShopProjectController::class, 'werkbon'])->name('projects.winkel.werkbon');
    Route::get('/projecten/{project}/winkel/werkbon.pdf', [ShopProjectController::class, 'werkbonPdf'])->name('projects.winkel.werkbon.pdf');
    Route::post('/projecten/{project}/winkel/bijlagen', [ShopProjectController::class, 'storeAttachments'])->name('projects.winkel.attachments.store');
    Route::delete('/projecten/{project}/winkel/bijlagen/{document}', [ShopProjectController::class, 'destroyAttachment'])->name('projects.winkel.attachments.destroy');
    Route::post('/projecten/{project}/archiveren', [ProjectController::class, 'archive'])->name('projects.archive');
    Route::post('/projecten/{project}/terugzetten', [ProjectController::class, 'restore'])->name('projects.restore');
    Route::delete('/projecten/{project}', [ProjectController::class, 'destroy'])->name('projects.destroy');
    Route::post('/projecten/{project}/bronbestanden', [SourceUpdateController::class, 'store'])->name('projects.sources.store');
    Route::get('/projecten/bronbestanden/{token}', [SourceUpdateController::class, 'review'])->name('projects.sources.review');
    Route::post('/projecten/bronbestanden/{token}', [SourceUpdateController::class, 'confirm'])->name('projects.sources.confirm');
    Route::post('/projecten/{project}/bronbestanden/{document}/activeren', [SourceUpdateController::class, 'activate'])->name('projects.sources.activate')->scopeBindings();
    Route::post('/projecten/{project}/meetstaat', [ProjectController::class, 'storeMeetstaat'])->name('projects.meetstaat.store');
    Route::post('/projecten/{project}/opdrachtlijst', [ScreenExcelImportController::class, 'storeOnProject'])->name('projects.screens.store');
    Route::post('/projecten/{project}/plattegrond', [ProjectController::class, 'storePlattegrond'])->name('projects.plattegrond.store');
    Route::get('/projecten/{project}/documenten/{document}', [ProjectController::class, 'document'])->name('projects.documents.show');
    Route::post('/projecten/{project}/opdrachten', [ProjectController::class, 'storeOrder'])->name('projects.orders.store');
    Route::post('/projecten/{project}/taken/{areaTask}/gereed', [AreaTaskController::class, 'complete'])->name('projects.tasks.complete');
    Route::post('/projecten/{project}/ruimtes/details', [DrawingController::class, 'details'])->name('projects.areas.details');
    Route::post('/projecten/{project}/ruimtes/{area}/afvinken', [AreaTaskController::class, 'tick'])->name('projects.areas.tick');
    Route::get('/projecten/{project}/ruimtes/{area}', [DrawingController::class, 'area'])->name('projects.areas.show');
    Route::post('/projecten/{project}/ruimtes/{area}/onderdeel', [DrawingController::class, 'completeGroup'])->name('projects.areas.group');
    Route::post('/projecten/{project}/ruimtes/{area}/verwerken', [DrawingController::class, 'process'])->name('projects.areas.process');
    Route::post('/projecten/{project}/ruimtes/{area}/heropenen', [DrawingController::class, 'reopen'])->name('projects.areas.reopen');
    Route::post('/projecten/{project}/ruimtes/{area}/akkoord', [DrawingController::class, 'approve'])->name('projects.areas.approve');
    Route::post('/projecten/{project}/werkzaamheden/verwerken', [DrawingController::class, 'processMany'])->name('projects.work.process');
    Route::post('/projecten/{project}/werkzaamheden/selectie/verwerken', [DrawingController::class, 'processSelection'])->name('projects.areas.selection.process');
    Route::post('/projecten/{project}/werkzaamheden/heropenen', [DrawingController::class, 'reopenMany'])->name('projects.work.reopen');
    Route::post('/projecten/{project}/werkzaamheden/akkoord', [DrawingController::class, 'approveMany'])->name('projects.work.approve');
    Route::post('/projecten/{project}/ruimtes/{area}/marker', [DrawingController::class, 'place'])->name('projects.areas.marker');
    Route::post('/projecten/{project}/tekeningen/{document}/zoeken', [DrawingController::class, 'detect'])->name('projects.drawings.detect');
    Route::get('/projecten/{project}/opleverpunten', [SnagController::class, 'index'])->name('projects.snags.index');
    Route::get('/projecten/{project}/opleverpunten/pdf', [SnagController::class, 'export'])->name('projects.snags.export');
    Route::post('/projecten/{project}/opleverpunten', [SnagController::class, 'store'])->name('projects.snags.store');
    Route::get('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'show'])->name('projects.snags.show');
    Route::patch('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'update'])->name('projects.snags.update');
    Route::delete('/projecten/{project}/opleverpunten/{snag}', [SnagController::class, 'destroy'])->name('projects.snags.destroy');
    Route::post('/projecten/{project}/opleverpunten/{snag}/foto', [SnagController::class, 'photo'])->name('projects.snags.photos.store');
    Route::get('/projecten/{project}/opleverpunten/{snag}/foto/{photo}', [SnagController::class, 'file'])->name('projects.snags.photo');
    Route::post('/projecten/{project}/opleverpunten/{snag}/gereed', [SnagController::class, 'report'])->name('projects.snags.report');
    Route::post('/projecten/{project}/opleverpunten/{snag}/goedkeuren', [SnagController::class, 'approve'])->name('projects.snags.approve');
    Route::post('/projecten/{project}/opleverpunten/{snag}/afkeuren', [SnagController::class, 'reject'])->name('projects.snags.reject');
    Route::post('/projecten/{project}/opleverpunten/{snag}/link-intrekken', [SnagController::class, 'revokePublicLink'])->name('projects.snags.revoke');
    Route::get('/gebruikers', [UserController::class, 'index'])->name('users.index');
    Route::get('/gebruikers/nieuw', [UserController::class, 'create'])->name('users.create');
    Route::post('/gebruikers', [UserController::class, 'store'])->name('users.store');
    Route::get('/gebruikers/{user}', [UserController::class, 'show'])->name('users.show');
    Route::patch('/gebruikers/{user}', [UserController::class, 'update'])->name('users.update');
    Route::delete('/gebruikers/{user}', [UserController::class, 'destroy'])->name('users.destroy');
    Route::get('/beheer/werkzaamheden', [WorkActivityController::class, 'index'])->name('work-activities.index');
    Route::post('/beheer/werkzaamheden', [WorkActivityController::class, 'store'])->name('work-activities.store');
    Route::patch('/beheer/werkzaamheden/{activity}', [WorkActivityController::class, 'update'])->name('work-activities.update');
    Route::post('/beheer/werkzaamheden/categorieen', [WorkActivityCategoryController::class, 'store'])->name('work-activity-categories.store');
    Route::patch('/beheer/werkzaamheden/categorieen/{category}', [WorkActivityCategoryController::class, 'update'])->name('work-activity-categories.update');
    Route::get('/vakmensen', [WorkerController::class, 'index'])->name('workers.index');
    Route::get('/personeel', [WorkerPersonnelController::class, 'index'])->name('personnel.index');
    Route::patch('/personeel/{worker}/leden/{crewMember}/werkdagen', [WorkerPersonnelController::class, 'update'])->name('personnel.work-days.update');
    Route::redirect('/vakmensen/afwezigheid', '/personeel');
    Route::redirect('/vakmensen/personeel', '/personeel');
    Route::get('/vakmensen/nieuw', [WorkerController::class, 'create'])->name('workers.create');
    Route::post('/vakmensen', [WorkerController::class, 'store'])->name('workers.store');
    Route::post('/vakmensen/pdf', [WorkerPdfImportController::class, 'preview'])->name('workers.pdf.preview');
    Route::post('/vakmensen/pdf/teams', [WorkerPdfImportController::class, 'import'])->name('workers.pdf.import');
    Route::post('/vakmensen/vakkennis', [WorkerController::class, 'storeSpecialty'])->name('workers.specialties.store');
    Route::get('/vakmensen/{worker}', [WorkerController::class, 'show'])->name('workers.show');
    Route::post('/vakmensen/{worker}/inlog', [WorkerController::class, 'storeLogin'])->name('workers.login.store');
    Route::post('/vakmensen/{worker}/leden/{crewMember}/inlogbericht', [WorkerLoginInviteController::class, 'store'])->middleware('throttle:vakman-login-invite')->name('workers.login-invite.store');
    Route::post('/vakmensen/{worker}/leden/{crewMember}/inlogbericht/wachtwoord', [WorkerLoginInviteController::class, 'resetPassword'])->middleware('throttle:vakman-login-invite')->name('workers.login-invite.reset');
    Route::patch('/vakmensen/{worker}/leden/{crewMember}/actief', [WorkerCrewMemberController::class, 'updateActive'])->name('workers.crew-members.active.update');
    Route::delete('/vakmensen/{worker}/leden/{crewMember}', [WorkerCrewMemberController::class, 'destroy'])->name('workers.crew-members.destroy');
    Route::patch('/vakmensen/{worker}/actief', [WorkerController::class, 'updateActive'])->name('workers.active.update');
    Route::delete('/vakmensen/{worker}', [WorkerController::class, 'destroy'])->name('workers.destroy');
    Route::patch('/vakmensen/{worker}', [WorkerController::class, 'update'])->name('workers.update');
    Route::patch('/vakmensen/{worker}/vrijdag', [WorkerAvailabilityController::class, 'updateFriday'])->name('workers.friday.update');
    Route::patch('/vakmensen/{worker}/beschikbaarheid', [WorkerAvailabilityController::class, 'updateFlags'])->name('workers.availability.update');
    Route::post('/vakmensen/{worker}/beschikbaarheid', [WorkerAvailabilityController::class, 'store'])->name('workers.availability.store');
    Route::delete('/vakmensen/{worker}/beschikbaarheid/{availability}', [WorkerAvailabilityController::class, 'destroy'])->scopeBindings()->name('workers.availability.destroy');
    Route::post('/vakmensen/{worker}/prijzen', [WorkerRateController::class, 'store'])->name('workers.rates.store');
    Route::get('/ploegen', [TeamController::class, 'index'])->name('teams.index');
    Route::post('/ploegen', [TeamController::class, 'store'])->name('teams.store');
});
